import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ImageSlider from "@/components/ImageSlider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vedic Pandit",
  description: "Generated by Mine gate LLp",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <ImageSlider/>
        {children}</body>
    </html>
  );
}
